// ============================================================================
// FX CATALOG
// ============================================================================
// This is intentionally boring data. That is good!
//
// Each line is simply:
//     { "Brand", "Model Name", FAMILY_NUMBER },
//
// The audio engine does NOT contain one giant custom effect for every line.
// The catalog supplies names and a family/identity. The DSP uses that data to
// create a different deterministic personality.
//
// Beginner exercise:
//   Add one line, rebuild, and search for it in the plugin.
// ============================================================================

#pragma once
#include <juce_core/juce_core.h>

namespace BabyGirl
{
    struct FxCatalogItem
    {
        const char* brand;
        const char* model;
        int family;
    };

    // Nominative reference catalog: original DSP/UI, no manufacturer artwork
    // or proprietary assets. The names are labels; the implementation is ours.
    //
    // FAMILY NUMBERS
    // 0 Drive/Fuzz
    // 1 Dynamics
    // 2 EQ/Tone
    // 3 Delay/Echo
    // 4 Reverb/Space
    // 5 Modulation
    // 6 Filter
    // 7 Gate/De-Ess
    // 8 Pitch/Doubler
    // 9 Looper/Freeze
    // 10 Creative/Experimental
    inline constexpr FxCatalogItem kFxCatalog[] = {
    {"Boss", "DS-1", 0},
    {"Boss", "BD-2", 0},
    {"Boss", "OD-3", 0},
    {"Boss", "SD-1", 0},
    {"Boss", "MT-2", 0},
    {"Boss", "HM-2", 0},
    {"Boss", "CE-2", 5},
    {"Boss", "CE-5", 5},
    {"Boss", "CH-1", 10},
    {"Boss", "BF-3", 10},
    {"Boss", "PH-3", 10},
    {"Boss", "DD-3", 10},
    {"Boss", "DD-7", 10},
    {"Boss", "RV-6", 10},
    {"Boss", "RV-5", 10},
    {"Boss", "OC-5", 10},
    {"Boss", "RC-5", 10},
    {"Boss", "GE-7", 10},
    {"Boss", "NS-2", 10},
    {"Boss", "TU-3", 10},
    {"Boss", "SY-1", 10},
    {"Boss", "RE-2", 3},
    {"Boss", "DM-2", 10},
    {"Boss", "FZ-1W", 10},
    {"Mooer", "Black Secret", 10},
    {"Mooer", "Green Mile", 10},
    {"Mooer", "Yellow Comp", 1},
    {"Mooer", "Blues Crab", 10},
    {"Mooer", "Solo", 10},
    {"Mooer", "Triangle Buff", 10},
    {"Mooer", "E-Lady", 10},
    {"Mooer", "Ensemble King", 5},
    {"Mooer", "Mod Factory", 5},
    {"Mooer", "Echoverb", 3},
    {"Mooer", "Ocean Machine", 10},
    {"Mooer", "Radar", 10},
    {"Mooer", "Preamp Live", 0},
    {"Mooer", "Reecho", 3},
    {"Mooer", "Trelicopter", 10},
    {"Mooer", "ShimVerb", 10},
    {"Mooer", "Spark", 10},
    {"Mooer", "Tender Octaver", 8},
    {"Mooer", "Pitch Step", 8},
    {"Korg", "Sas-20", 10},
    {"Korg", "MS-20 Filter", 6},
    {"Korg", "Volca Delay", 3},
    {"Korg", "Kaoss Pad", 6},
    {"Korg", "DL-4 style Looper", 9},
    {"Korg", "Stage Echo", 3},
    {"Korg", "Mini Kaoss", 6},
    {"Korg", "Nu:Tekt Drive", 0},
    {"Roland", "Space Echo", 3},
    {"Roland", "Dimension D", 5},
    {"Roland", "JC Chorus", 5},
    {"Roland", "CE-1", 5},
    {"Roland", "RE-201", 3},
    {"Roland", "RE-301", 3},
    {"Roland", "Dimension C", 5},
    {"Roland", "DC-50", 10},
    {"Flamma", "FC01", 10},
    {"Flamma", "FC02", 10},
    {"Flamma", "FC03", 10},
    {"Flamma", "FC04", 10},
    {"Flamma", "FC05", 10},
    {"Flamma", "FS01", 10},
    {"Flamma", "FS02", 10},
    {"Flamma", "FS03", 10},
    {"Flamma", "FS06", 10},
    {"Flamma", "FS07", 10},
    {"Flamma", "FS08", 10},
    {"Flamma", "FS09", 10},
    {"Flamma", "FS22", 10},
    {"MXR", "Phase 90", 5},
    {"MXR", "Phase 95", 5},
    {"MXR", "Dyna Comp", 1},
    {"MXR", "M87 Bass Comp", 1},
    {"MXR", "Carbon Copy", 10},
    {"MXR", "Super Badass Distortion", 0},
    {"MXR", "10 Band EQ", 2},
    {"MXR", "Analog Chorus", 5},
    {"MXR", "Flanger", 5},
    {"MXR", "Micro Amp", 10},
    {"Electro-Harmonix", "Big Muff", 0},
    {"Electro-Harmonix", "Small Clone", 10},
    {"Electro-Harmonix", "Memory Man", 3},
    {"Electro-Harmonix", "Holy Grail", 4},
    {"Electro-Harmonix", "Soul Food", 10},
    {"Electro-Harmonix", "Bass Big Muff", 0},
    {"Electro-Harmonix", "Metal Muff", 0},
    {"Electro-Harmonix", "Freeze", 10},
    {"Electro-Harmonix", "Pitch Fork", 8},
    {"Electro-Harmonix", "Hot Tubes", 0},
    {"Electro-Harmonix", "Canyon", 3},
    {"TC Electronic", "Flashback", 3},
    {"TC Electronic", "Hall of Fame", 4},
    {"TC Electronic", "Corona Chorus", 5},
    {"TC Electronic", "Shaker Vibrato", 5},
    {"TC Electronic", "Sub'n'Up", 10},
    {"TC Electronic", "HyperGravity", 1},
    {"TC Electronic", "Mimiq", 10},
    {"TC Electronic", "Spark Booster", 0},
    {"TC Electronic", "Sentry", 10},
    {"Line 6", "DL4", 10},
    {"Line 6", "MM4", 10},
    {"Line 6", "FM4", 10},
    {"Line 6", "DM4", 10},
    {"Line 6", "M5", 10},
    {"Line 6", "M9", 10},
    {"Line 6", "M13", 10},
    {"Line 6", "HX-style Poly Pitch", 8},
    {"Line 6", "Helix-style Chorus", 5},
    {"Eventide", "H3000", 10},
    {"Eventide", "Space", 10},
    {"Eventide", "Blackhole", 4},
    {"Eventide", "TimeFactor", 3},
    {"Eventide", "ModFactor", 5},
    {"Eventide", "PitchFactor", 8},
    {"Eventide", "Micropitch", 8},
    {"Eventide", "Ultratap", 0},
    {"Universal Audio", "1176", 1},
    {"Universal Audio", "LA-2A", 1},
    {"Universal Audio", "Pultec EQ", 2},
    {"Universal Audio", "Galaxy Tape Echo", 3},
    {"Universal Audio", "Brigade Chorus", 5},
    {"Universal Audio", "Oxide Tape", 10},
    {"Neve", "1073 Preamp", 2},
    {"Neve", "1084 EQ", 2},
    {"Neve", "2254 Compressor", 1},
    {"Neve", "33609 Compressor", 1},
    {"Neve", "Portico Saturator", 0},
    {"SSL", "G Bus Compressor", 1},
    {"SSL", "E-Channel", 10},
    {"SSL", "4K EQ", 2},
    {"SSL", "De-Ess", 7},
    {"SSL", "Fusion HF Compressor", 1},
    {"API", "550A EQ", 2},
    {"API", "550B EQ", 2},
    {"API", "560 Graphic EQ", 2},
    {"API", "2500 Compressor", 1},
    {"API", "512 Preamp", 0},
    {"Fairchild", "670 Compressor", 1},
    {"Fairchild", "660 Compressor", 1},
    {"dbx", "160 Compressor", 1},
    {"dbx", "165 Compressor", 1},
    {"dbx", "166 Compressor", 1},
    {"dbx", "120A Subharmonic", 8},
    {"Lexicon", "PCM Reverb", 4},
    {"Lexicon", "224 Hall", 4},
    {"Lexicon", "480L Hall", 4},
    {"EMT", "140 Plate", 4},
    {"EMT", "250 Reverb", 4},
    {"EMT", "246 Compressor", 1},
    {"Fender", "Spring Reverb", 4},
    {"Fender", "Tube Tremolo", 5},
    {"Fender", "Bassman Drive", 0},
    {"Fender", "Deluxe Tremolo", 5},
    {"Vox", "AC Drive", 0},
    {"Vox", "V847 Wah", 6},
    {"Vox", "Repeat Percussion", 10},
    {"Vox", "Treble Booster", 0},
    {"Orange", "Rocker Drive", 0},
    {"Orange", "Terror Gain", 10},
    {"Orange", "Graphic EQ", 2},
    {"Peavey", "5150 Drive", 0},
    {"Peavey", "Classic Chorus", 5},
    {"Peavey", "ValveKing Gate", 7},
    {"Ampeg", "SVT Drive", 0},
    {"Ampeg", "Scrambler", 10},
    {"Ampeg", "Opto Comp", 1},
    {"Ampeg", "Bass Envelope", 6},
    {"Darkglass", "B3K Drive", 0},
    {"Darkglass", "Microtubes", 0},
    {"Darkglass", "Hyper Luminal", 10},
    {"Darkglass", "Alpha Omega Drive", 0},
    {"Aguilar", "Tone Hammer", 10},
    {"Aguilar", "Compressor", 1},
    {"Aguilar", "Filter Twin", 6},
    {"Aguilar", "Octamizer", 8},
    {"Chase Bliss", "Mood-style Delay", 3},
    {"Chase Bliss", "Warped Vinyl", 10},
    {"Chase Bliss", "Blooper-style Looper", 9},
    {"Chase Bliss", "Habit-style Delay", 3},
    {"Source Audio", "Collider", 10},
    {"Source Audio", "Nemesis", 10},
    {"Source Audio", "Ventris", 4},
    {"Source Audio", "C4-style Synth", 10},
    {"Source Audio", "Spectrum Filter", 2},
    {"EarthQuaker Devices", "Plumes", 0},
    {"EarthQuaker Devices", "Hoof", 0},
    {"EarthQuaker Devices", "Avalanche Run", 10},
    {"EarthQuaker Devices", "Afterneath", 4},
    {"EarthQuaker Devices", "Dispatch Master", 10},
    {"EarthQuaker Devices", "Arrows", 10},
    {"Walrus Audio", "Julia", 5},
    {"Walrus Audio", "Slö", 4},
    {"Walrus Audio", "Fathom", 4},
    {"Walrus Audio", "ARP-87", 10},
    {"Walrus Audio", "Iron Horse", 0},
    {"Walrus Audio", "R1 Reverb", 4},
    {"JHS", "Morning Glory", 10},
    {"JHS", "PackRat", 0},
    {"JHS", "3 Series Reverb", 4},
    {"JHS", "Colour Box", 10},
    {"JHS", "Angry Charlie", 10},
    {"ProCo", "RAT", 0},
    {"ProCo", "Turbo RAT", 0},
    {"Fulltone", "OCD", 10},
    {"Fulltone", "Fulldrive", 0},
    {"Fulltone", "DejaVibe", 10},
    {"ISP", "Decimator Gate", 7},
    {"ISP", "Theta Preamp", 0},
    {"Digitech", "Whammy", 8},
    {"Digitech", "Drop", 8},
    {"Digitech", "Polara", 10},
    {"Digitech", "HardWire Delay", 3},
    {"Digitech", "Ricochet", 8},
    {"Pigtronix", "Infinity Looper", 9},
    {"Pigtronix", "Echolution", 3},
    {"Pigtronix", "Philosopher's Tone", 10},
    {"Eventide Blackhole", "Blackhole Reverb", 4},
    {"Roland/Boss", "Slicer", 5},
    {"Roland/Boss", "Slow Gear", 10},
    {"Roland/Boss", "Pitch Shifter", 8},
    {"Maestro", "Fuzz-Tone", 0},
    {"Maestro", "Echoplex", 3},
    {"Mutron", "Phasor", 10},
    {"Mutron", "Envelope Filter", 6},
    {"Morley", "Wah", 6},
    {"Morley", "Bad Horsie", 10},
    {"Xotic", "EP Booster", 0},
    {"Xotic", "BB Preamp", 0},
    {"Xotic", "SP Compressor", 1},
    {"Bogner", "Ecstasy Drive", 0},
    {"Bogner", "Burnley", 10},
    {"Friedman", "BE-OD", 10},
    {"Friedman", "Buxom Boost", 0},
    {"Suhr", "Riot", 0},
    {"Suhr", "Koji Comp", 1},
    {"Zvex", "Fuzz Factory", 0},
    {"Zvex", "Super Duper", 10},
    {"Zvex", "Instant Lo-Fi", 10},
    {"Death By Audio", "Fuzz War", 0},
    {"Death By Audio", "Eternal Youth", 10},
    {"Death By Audio", "Echo Dream", 3},
    {"Alexander", "Super Neo-Matic", 10},
    {"Alexander", "Syntax Error", 10},
    {"Meris", "Mercury7", 4},
    {"Meris", "Ottobit Jr", 10},
    {"Meris", "Polymoon", 3},
    {"Meris", "Enzo", 10},
    {"Blackstar", "HT Drive", 0},
    {"Blackstar", "Dept. 10 Boost", 0},
    {"Laney", "Ironheart Drive", 0},
    {"Laney", "Supergroup Tremolo", 5},
    {"Yamaha", "SPX-style Multi FX", 10},
    {"Yamaha", "Compressor", 1},
    {"Digitech/DOD", "250 Overdrive", 0},
    {"Digitech/DOD", "FX80B Compressor", 1},
    {"Digitech/DOD", "Gonkulator", 10},
    {"Ibanez", "TS9", 0},
    {"Ibanez", "TS808", 0},
    {"Ibanez", "TS Mini", 0},
    {"Ibanez", "Flanger FL9", 5},
    {"Ibanez", "Chorus CS9", 5},
    {"Ibanez", "Analog Delay AD9", 3},
    {"Ibanez", "Tube Screamer Mini", 0},
    {"Strymon", "Timeline", 3},
    {"Strymon", "BigSky", 3},
    {"Strymon", "Mobius", 5},
    {"Strymon", "El Capistan", 3},
    {"Strymon", "Deco", 0},
    {"Strymon", "Riverside", 0},
    {"Strymon", "Sunset", 0},
    {"Strymon", "Compadre", 1},
    {"Strymon", "Cloudburst", 4},
    {"Strymon", "Volante", 3},
    {"Keeley", "Compressor Plus", 1},
    {"Keeley", "Katana Boost", 0},
    {"Keeley", "Monterey", 0},
    {"Keeley", "Mag Echo", 3},
    {"Keeley", "Dark Side", 0},
    {"Keeley", "Caverns", 4},
    {"Wampler", "Plexi-Drive", 0},
    {"Wampler", "Tumnus", 0},
    {"Wampler", "Ego Compressor", 1},
    {"Wampler", "Terraform", 5},
    {"Wampler", "Dracarys", 0},
    {"Wampler", "Reflection", 0},
    {"Catalinbread", "Belle Epoch", 3},
    {"Catalinbread", "Topanga", 4},
    {"Catalinbread", "Sabbra Cadabra", 0},
    {"Catalinbread", "Dirty Little Secret", 0},
    {"Catalinbread", "Karma Suture", 0},
    {"J. Rockett", "Archer", 0},
    {"J. Rockett", "Blue Note", 0},
    {"J. Rockett", "El Hombre", 0},
    {"J. Rockett", "The Dude", 0},
    {"J. Rockett", "Clockwork Echo", 3},
    {"Tech 21", "SansAmp", 0},
    {"Tech 21", "Bass Driver DI", 0},
    {"Tech 21", "Fly Rig", 0},
    {"Tech 21", "Q-Strip", 2},
    {"Tech 21", "Blonde", 0},
    {"EBS", "MultiComp", 1},
    {"EBS", "ValveDrive", 0},
    {"EBS", "BassIQ", 6},
    {"EBS", "DynaVerb", 1},
    {"Mad Professor", "Sweet Honey", 0},
    {"Mad Professor", "Forest Green", 0},
    {"Mad Professor", "Royal Blue", 0},
    {"Mad Professor", "Golden Cello", 0},
    {"Pigtronix", "Mothership", 0},
    {"Pigtronix", "Disnortion", 0},
    {"Pigtronix", "Tremvelope", 5},
    {"FMR Audio", "RNC Compressor", 1},
    {"FMR Audio", "RNLA Limiter", 1},
    {"Warm Audio", "WA76", 0},
    {"Warm Audio", "WA2A", 0},
    {"Warm Audio", "EQP-WA", 2},
    {"Empirical Labs", "Distressor", 1},
    {"Empirical Labs", "EL8 Fatso", 0},
    {"Manley", "Vari-Mu", 0},
    {"Manley", "Massive Passive", 2},
    {"Manley", "VoxBox", 0},
    {"Chandler", "TG2 Preamp", 0},
    {"Chandler", "TG1 Limiter", 1},
    {"Trident", "A-Range EQ", 2},
    {"Trident", "S-80 EQ", 2},
    {"Drawmer", "1968 Compressor", 1},
    {"Drawmer", "DS201 Gate", 7},
    {"Eventide", "Blackhole", 0},
    {"Eventide", "TriceraChorus", 5},
    {"Eventide", "Rose Delay", 3},
    {"Eventide", "UltraTap", 0},
    {"TC Helicon", "VoiceLive-style Doubler", 8},
    {"TC Helicon", "Harmony Singer", 8},
    {"RME", "ADI-2 EQ", 2},
    {"Roland", "Dimension S", 0},
    {"Roland", "DC-2W", 0},
    {"Roland", "RE-20", 0},
    {"Roland", "JC-120 Chorus", 5},
    {"Flamma", "FS02 Reverb", 4},
    {"Flamma", "FS03 Delay", 3},
    {"Flamma", "FS04 Distortion", 0},
    {"Flamma", "FS05 Chorus", 5},
    {"Flamma", "FS06 Modulation", 5},
    {"Flamma", "FS08 Digital Delay", 3},
    {"Flamma", "FS09 Reverb", 4},
    {"Mooer", "Radar CAB", 0},
    {"Mooer", "Micro DI", 0},
    {"Mooer", "Micro Preamp 005", 0},
    {"Mooer", "Micro Preamp 011", 0},
    {"Mooer", "Micro Power", 0},
    {"Korg", "Kaoss Pad 3", 0},
    {"Korg", "Kaoss Pad KP2", 0},
    {"Korg", "Monotron Filter", 6},
    {"Korg", "SQ-1 Filter", 6},
    {"Strymon", "Timeline", 3}, {"Strymon", "BigSky", 4}, {"Strymon", "Mobius", 5}, {"Strymon", "Volante", 3}, {"Strymon", "Iridium", 0},
    {"Chase Bliss", "Mood-style", 9}, {"Chase Bliss", "Habit-style", 3}, {"Chase Bliss", "Blooper-style", 9}, {"Chase Bliss", "Warp-style", 8},
    {"EarthQuaker Devices", "Plumes", 0}, {"EarthQuaker Devices", "Avalanche Run", 3}, {"EarthQuaker Devices", "Afterneath", 4}, {"EarthQuaker Devices", "Rainbow Machine", 8}, {"EarthQuaker Devices", "Hoof", 0},
    {"Walrus Audio", "Julia", 5}, {"Walrus Audio", "Slö", 4}, {"Walrus Audio", "ARP-87", 3}, {"Walrus Audio", "Fathom", 4}, {"Walrus Audio", "Polychrome", 5},
    {"JHS", "Morning Glory", 0}, {"JHS", "Angry Charlie", 0}, {"JHS", "3 Series Chorus", 5}, {"JHS", "3 Series Reverb", 4}, {"JHS", "Panther Cub", 3},
    {"Wampler", "Plexi-Drive", 0}, {"Wampler", "Tumnus", 0}, {"Wampler", "Terraform", 5}, {"Wampler", "Ego Compressor", 1}, {"Wampler", "Ethereal", 4},
    {"Keeley", "Compressor Plus", 1}, {"Keeley", "Caverns", 4}, {"Keeley", "Delay Workstation", 3}, {"Keeley", "Synth-1", 8}, {"Keeley", "Katana Boost", 0},
    {"Digitech", "Whammy", 8}, {"Digitech", "Drop", 8}, {"Digitech", "Polara", 4}, {"Digitech", "Obscura", 3}, {"Digitech", "Trio-style", 9},
    {"Ibanez", "Tube Screamer", 0}, {"Ibanez", "FL-9", 5}, {"Ibanez", "CS-9", 5}, {"Ibanez", "AD-9", 3}, {"Ibanez", "Weeping Demon", 6},
    {"ProCo", "RAT", 0}, {"ProCo", "Turbo RAT", 0}, {"ProCo", "Deucetone", 0}, {"ProCo", "Turbo Rat", 0},
    {"Fulltone", "OCD", 0}, {"Fulltone", "Fulldrive", 0}, {"Fulltone", "DejaVibe", 5}, {"Fulltone", "Tube Tape Echo", 3},
    {"Zvex", "Fuzz Factory", 0}, {"Zvex", "Box of Rock", 0}, {"Zvex", "Instant Lo-Fi Junky", 5}, {"Zvex", "Super Duper", 0},
    {"Xotic", "EP Booster", 0}, {"Xotic", "SP Compressor", 1}, {"Xotic", "BB Preamp", 0}, {"Xotic", "Super Sweet", 0},
    {"Catalinbread", "Belle Epoch", 3}, {"Catalinbread", "Sabbra Cadabra", 0}, {"Catalinbread", "Topanga", 4}, {"Catalinbread", "Karma Suture", 0},
    {"Source Audio", "Collider", 3}, {"Source Audio", "Nemesis", 3}, {"Source Audio", "Ventris", 4}, {"Source Audio", "C4 Synth", 8}, {"Source Audio", "Spectrum Filter", 6},
    {"Meris", "Mercury7", 4}, {"Meris", "Polymoon", 3}, {"Meris", "Enzo", 8}, {"Meris", "Ottobit", 10}, {"Meris", "LVX", 3},
    {"Tech 21", "SansAmp", 0}, {"Tech 21", "Bass Driver", 0}, {"Tech 21", "Fly Rig Plexi", 0}, {"Tech 21", "Q Strip", 2},
    {"Darkglass", "Microtubes", 0}, {"Darkglass", "B7K", 0}, {"Darkglass", "Vintage Deluxe", 0}, {"Darkglass", "Hyper Luminal", 1},
    {"Aguilar", "Tone Hammer", 0}, {"Aguilar", "DB 925", 2}, {"Aguilar", "TLC Compressor", 1}, {"Aguilar", "Filter Twin", 6},
    {"Ampeg", "SVT-style Preamp", 0}, {"Ampeg", "SCR-DI", 0}, {"Ampeg", "SVX-style Drive", 0}, {"Ampeg", "Opto Comp", 1},
    {"EBS", "MultiComp", 1}, {"EBS", "BassIQ", 6}, {"EBS", "DynaVerb", 4}, {"EBS", "OctaBass", 8},
    {"Friedman", "BE-OD", 0}, {"Friedman", "Buxom Boost", 0}, {"Friedman", "BE-100 Preamp", 0}, {"Friedman", "Golden Pearl", 0},
    {"Bogner", "Ecstasy Drive", 0}, {"Bogner", "La Grange", 0}, {"Bogner", "Burnley", 0}, {"Bogner", "Fish Preamp", 0},
    {"Vox", "AC30 Tremolo", 5}, {"Vox", "AC30 Top Boost", 0}, {"Vox", "Tone Bender-style", 0}, {"Vox", "Repeater Echo", 3},
    {"Marshall", "Bluesbreaker", 0}, {"Marshall", "Guvernor", 0}, {"Marshall", "ShredMaster", 0}, {"Marshall", "DSL Preamp", 0},
    {"Mesa/Boogie", "Mark-style Lead", 0}, {"Mesa/Boogie", "Rectifier-style", 0}, {"Mesa/Boogie", "Graphic EQ", 2}, {"Mesa/Boogie", "Cab Clone", 0},
    {"Peavey", "5150-style", 0}, {"Peavey", "6505-style", 0}, {"Peavey", "Triple XXX-style", 0}, {"Peavey", "T-Max Bass", 0},
    {"DOD", "250 Overdrive", 0}, {"DOD", "FX65 Chorus", 5}, {"DOD", "FX90 Delay", 3}, {"DOD", "Grind Distortion", 0},
    {"RAT", "Vintage Distortion", 0}, {"EHX", "Electric Mistress", 5}, {"EHX", "Poly Chorus", 5}, {"EHX", "Deluxe Memory Man", 3}, {"EHX", "Cathedral", 4},
    {"BOSS", "OC-2", 8}, {"BOSS", "PH-2", 5}, {"BOSS", "BF-2", 5}, {"BOSS", "DM-3", 3}, {"BOSS", "RV-3", 4},
    {"Roland", "SDE-1000", 3}, {"Roland", "SDE-3000", 3}, {"Roland", "VP-330 style", 10}, {"Roland", "SH-101 filter", 6},
    {"Korg", "DL-8000R", 3}, {"Korg", "A3-style multi FX", 10}, {"Korg", "Pandora-style FX", 10}, {"Korg", "Trinity-style FX", 10},
    {"Mooer", "GE-style Multi FX", 10}, {"Mooer", "Ocean Machine", 3}, {"Mooer", "E7 Poly Synth", 8}, {"Mooer", "Ensemble King", 5},
    {"Flamma", "FC05 Multi Mod", 5}, {"Flamma", "FS01 Drum Machine", 9}, {"Flamma", "FS07 Chorus", 5}, {"Flamma", "FS08 Delay", 3},
    {"Eventide", "Blackhole", 4}, {"Eventide", "H910-style Pitch", 8}, {"Eventide", "H949-style Pitch", 8}, {"Eventide", "Omnipressor-style", 1},
    {"Lexicon", "Prime Time-style Delay", 3}, {"Lexicon", "PCM70-style", 4}, {"Lexicon", "300-style", 4}, {"Lexicon", "Reflex-style", 4},
    {"TC Electronic", "2290-style Delay", 3}, {"TC Electronic", "M-One-style", 10}, {"TC Electronic", "G-System-style", 10}, {"TC Electronic", "SCF Chorus", 5},
    {"Urei", "1176", 1}, {"Urei", "LA-4", 1}, {"UREI", "1178", 1}, {"UREI", "1176AE", 1},
    {"Manley", "Variable Mu", 1}, {"Manley", "Massive Passive", 2}, {"Manley", "ELOP", 1}, {"Manley", "VoxBox", 1},
    {"Empirical Labs", "Distressor", 1}, {"Empirical Labs", "EL8-style", 1}, {"Empirical Labs", "Mike-E", 1},
    {"Drawmer", "1960", 1}, {"Drawmer", "DS201", 7}, {"Drawmer", "1973", 2}, {"Drawmer", "DL241", 1},
    {"Focusrite", "ISA-style Preamp", 0}, {"Focusrite", "Red-style Compressor", 1}, {"Focusrite", "Red-style EQ", 2},
    {"Avalon", "VT-737-style", 1}, {"Avalon", "747-style", 2}, {"Avalon", "U5-style DI", 0},
    {"API", "5500 EQ", 2}, {"API", "560 EQ", 2}, {"API", "2500", 1}, {"API", "312 Preamp", 0},
    {"SSL", "E-Series Bus", 1}, {"SSL", "G-Series EQ", 2}, {"SSL", "Fusion", 10}, {"SSL", "SiX Channel", 10},
    {"Neve", "1073", 2}, {"Neve", "1081", 2}, {"Neve", "2254", 1}, {"Neve", "33609", 1},
    {"Pultec", "EQP-1A", 2}, {"Pultec", "MEQ-5", 2}, {"Pultec", "HME-3D", 2},
    {"Fairchild", "660", 1}, {"Fairchild", "670", 1}, {"Fairchild", "Level-Loc style", 1},
    {"dbx", "160XT", 1}, {"dbx", "165A", 1}, {"dbx", "160SL", 1}, {"dbx", "902 De-Esser", 7},
    {"Aphex", "Aural Exciter", 10}, {"Aphex", "Compellor", 1}, {"Aphex", "Dominion", 10},
    {"Eventide", "H3000 Factory-style", 10}, {"Eventide", "Blackhole", 4}, {"Eventide", "UltraTap", 3},
    {"Roland", "RE-301", 3}, {"Roland", "RE-501", 3}, {"Roland", "Dimension D", 5}, {"Roland", "DC-2", 5},
    {"Korg", "Stage Echo", 3}, {"Korg", "Dynacord-style Echo", 3}, {"Korg", "Monotron Delay", 3},
    {"Hughes & Kettner", "Tube Factor", 0}, {"Hughes & Kettner", "Rotosphere", 5}, {"Hughes & Kettner", "Warp Factor", 0},
    {"Line 6", "Echo Pro", 3}, {"Line 6", "Filter Pro", 6}, {"Line 6", "Mod Pro", 5}, {"Line 6", "M13-style Scene", 10},
    {"Boss", "SY-300 style", 8}, {"Boss", "GT-style Multi FX", 10}, {"Boss", "GT-100 style", 10}, {"Boss", "MS-3 style", 10},
    {"Fractal", "Amp Block-style Drive", 0}, {"Fractal", "Multiband Compressor", 1}, {"Fractal", "Multi Delay", 3}, {"Fractal", "Multi Reverb", 4},
    {"Neural DSP", "Modern Drive", 0}, {"Neural DSP", "Chorus", 5}, {"Neural DSP", "Pitch", 8}, {"Neural DSP", "Reverb", 4},
    {"Plugin Alliance", "Console-style Channel", 10}, {"Plugin Alliance", "Bus Compressor", 1}, {"Plugin Alliance", "Mega Reverb", 4},
    {"FabFilter", "Pro-Q-style EQ", 2}, {"FabFilter", "Pro-C-style Compressor", 1}, {"FabFilter", "Pro-R-style Reverb", 4}, {"FabFilter", "Saturn-style Saturator", 0},
    {"Soundtoys", "Decapitator-style", 0}, {"Soundtoys", "EchoBoy-style", 3}, {"Soundtoys", "Little Plate-style", 4}, {"Soundtoys", "FilterFreak-style", 6},
    {"iZotope", "Ozone-style Master", 10}, {"iZotope", "Trash-style Distortion", 0}, {"iZotope", "Neutron-style Channel", 10}, {"iZotope", "Stutter Edit-style", 9},
    {"MeldaProduction", "Multiband FX", 10}, {"MeldaProduction", "Morphing Filter", 6}, {"MeldaProduction", "Spectral Delay", 3},
    };

    inline constexpr int kFxCatalogSize = (int)(sizeof(kFxCatalog) / sizeof(kFxCatalog[0]));

    inline const char* familyName(int f)
    {
        switch (f)
        {
            case 0: return "DRIVE / FUZZ";
            case 1: return "DYNAMICS";
            case 2: return "EQ / TONE";
            case 3: return "DELAY / ECHO";
            case 4: return "REVERB / SPACE";
            case 5: return "MODULATION";
            case 6: return "FILTER";
            case 7: return "GATE / DE-ESS";
            case 8: return "PITCH / DOUBLER";
            case 9: return "LOOPER / FREEZE";
            default: return "CREATIVE / SPECIAL";
        }
    }
}
